AllCops:
  Exclude:
    - passpartu.gemspec
    - spec/**/*.rb
    - spec/*.rb

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 15
