admin:
  orders:
    create: false
    edit: false
    delete: false
  products:
    create: true
    edit: true
    delete: true
  items:
    crud: true
manager:
  orders:
    create: true
    edit: true
    delete: false
  products:
    create: true
    edit: true
    delete: false
